### ISSUE TITLE
推荐的基金这个功能是能用的了吗？

### ISSUE THREAD

**Issue by luolovehk** [olixu/Fund#1]
微信推送  只收到 这些内容，没有推荐的内容

今日基金推荐
建议申购的基金
建议赎回的基金

**Comment by olixu** [comment]
可以使用的。

难怪我前两天白天收到了推荐，是我推送的Key没改，等有时间改一下。

因为基金不像股票有实时的交易价格，基金只有净值和估值，而当天的估值在一些app中(例如天天基金app)，可以很容易看到当天的实时行情，虽然估值有误差，但是基本相差不大，所以在交易日当天下午3点前交易时，其实直接看那些app就行了。

我这个程序主要的任务是对净值做宏观上的分析，例如分析 '日涨跌幅', '最近一周涨跌幅', '最近一月涨跌幅', '最近三周涨跌幅', '最近六涨跌幅', '最近一年涨跌幅', '最近两年涨跌幅', '最近三年涨跌幅', '今年以来涨跌幅', '成立以来涨跌幅'等参数来进行选择，具体的策略需要自行根据行情设定。

通过我过去两个月的实际操作，发现程序做波段还是可以的，例如五月中旬到六月中旬大盘在震荡，还是可以的。

比如假设过去一周，某个基金涨了10个点，那你就可以通过这个程序提前通知你，等到下一个交易日，看看有没有机会赎回。

比如假设过去一周，某个基金跌了10个点，那你就可以通过这个程序提前通知你，等到下一个交易日，看看有没有机会申购。

脚本默认的策略是：'最近一年涨跌幅']>50，'最近一周涨跌幅']<-2.0，'最近一周涨跌幅']>5.0 ，可以根据当前的行情设定自己的策略，因为不同时候的行情状态是不同的，例如大盘主力一直在拉升，那你可能就要考虑换策略了等等。

我本地设置的晚上11点半运行脚本，因为这时候所有的基金基本上都已经更新好了净值，我是Windows10系统，设定定时运行。11点半我能对市场整体有个宏观的了解，等到下一个交易日心中有点数。

脚本只能在交易日运行才会有结果，因为非交易日没有行情。

**Comment by luolovehk** [comment]
非常感谢您的热心解答，我就是喜欢这个功能，我是5号周日那天运行的，刚好不是交易日
